# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/mobile/v2/service/user/delete-user-endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/mobile/v2/service/user/delete-user-endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?systems/ajax/mobile/v2/service/user/delete-user-endpoints.proto\x12#systems.ajax.mobile.v2.service.user\x1aIsystems/ajax/api/mobile/v2/common/user/user-delete-account-response.proto\x1aMsystems/ajax/api/mobile/v2/common/user/user-delete-verification-request.proto\x1aNsystems/ajax/api/mobile/v2/common/user/user-delete-verification-response.proto\x1aHsystems/ajax/api/mobile/v2/common/user/user-delete-account-request.proto2\xcb\x02\n\x11\x44\x65leteUserService\x12\x91\x01\n\ndeleteUser\x12@.systems.ajax.api.mobile.v2.common.user.UserDeleteAccountRequest\x1a\x41.systems.ajax.api.mobile.v2.common.user.UserDeleteAccountResponse\x12\xa1\x01\n\x10sendVerification\x12\x45.systems.ajax.api.mobile.v2.common.user.UserDeleteVerificationRequest\x1a\x46.systems.ajax.api.mobile.v2.common.user.UserDeleteVerificationResponseB-\n#systems.ajax.mobile.v2.service.userP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.mobile.v2.service.user.delete_user_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n#systems.ajax.mobile.v2.service.userP\001\210\001\001\272\002\000'
  _globals['_DELETEUSERSERVICE']._serialized_start=413
  _globals['_DELETEUSERSERVICE']._serialized_end=744
# @@protoc_insertion_point(module_scope)
