# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/hub/user/hub_user.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/hub/user/hub_user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n9systems/ajax/api/mobile/v2/common/hub/user/hub_user.proto\x12*systems.ajax.api.mobile.v2.common.hub.user\x1a>systems/ajax/api/mobile/v2/common/hub/user/hub_user_type.proto\"\\\n\x07HubUser\x12\n\n\x02id\x18\x01 \x01(\t\x12\x45\n\x04role\x18\x02 \x01(\x0e\x32\x37.systems.ajax.api.mobile.v2.common.hub.user.HubUserTypeBA\n*systems.ajax.api.mobile.v2.common.hub.userP\x01\x88\x01\x01\xba\x02\rCommonHubUserb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.hub.user.hub_user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*systems.ajax.api.mobile.v2.common.hub.userP\001\210\001\001\272\002\rCommonHubUser'
  _globals['_HUBUSER']._serialized_start=169
  _globals['_HUBUSER']._serialized_end=261
# @@protoc_insertion_point(module_scope)
